### ISSUE TITLE
Explain better the new structure of collections in Scala 2.13

### ISSUE THREAD

**Issue by jvican** [scala/docs.scala-lang#1097]
The collections in Scala 2.13 contain the bare minimum that is useful to all Scala developers. However, nowhere it's explained that there exists another module called [scala-collection-contrib](https://github.com/scala/scala-collection-contrib), that is a Community-maintained project that extends the Scala core with more collections: `MultiSet`, `MultiDict`, `SeqMap` (soon), etc.
  
The idea of this ticket is to better explain this new structure and make it accessible to all Scala developers to find this Community-maintained module in case they either want to use it or add their own collection.
  
We could move some of the information in [this FAQ](https://github.com/scala/collection-strawman/wiki/FAQ#are-there-new-collection-types) to the new website.
  
Looping in @szeiger @julienrf @mdedetrich

**Comment by mdedetrich** [comment]
@jvican Just a tidbit, but when you say

> The collections in Scala 2.13 contain the bare minimum that is useful to all Scala developers

This definition sounds a bit subjective/ambiguous (it also seems to be a change of direction from what the Scala collections are as of today).

Personally I don't have an issue if `VectorMap` (i.e. a concrete implementation of `SeqMap`) is added into scala-collection-contrib and `SeqMap` is added into the stdlib, but if I wanted to be consistent with this line of thinking there would be quite a lot of collections that I would remove from stdlib and put into scala-collection-contrib (`Vector` is an immediate one that comes to mind, most people just (or should) just use `List` because of the various well known properties that `Vector` has).

It would be good to have some sought of consistent definition of what is "bare minimum"

**Comment by adriaanm** [comment]
"core" is a bit ambiguous. The collections are essential to Scala. They may not be mentioned in the spec, except for a few "core" types, but they are "core" to the experience of programming in Scala. It's important that we have a complete set of collections types and performant implementations. Yes, we are taking on a maintenance burden for every collection type we add -- but it's usually worth it! (By all means, let's discuss whether we think it's worth it for each type we add, or revisit those that are already there, but let's do it from the viewpoint that collections are key for the Scala programming experience.)

(That said, there's a smaller subset of Scala that's truly "core", as in, you couldn't implement the spec without them, but they are more of academic interest.)

**Comment by som-snytt** [comment]
Thanks, I didn't know about the `contrib` module. I would have called it `uncollected-collections`, or `uncollections` for short.

I didn't ask many questions on SO b/c only worth 5 points, but I got a great [answer](https://stackoverflow.com/a/40083398/1296806) from sjrd & densh for "What types are special to the compiler?" I don't know whether to update that answer or ask, "What collection types are the bare minimum to implement the spec? have a joyful developer experience? not alienate users?"

Taking on maintenance burden for collections is worth it because then we get to learn something from ichoran.

**Comment by SethTisue** [comment]
overall, I think the 2.13 collections docs are in good shape

scala-collection-contrib specifically isn't mentioned, but we haven't published it yet; I made a note about publicity/docs at https://github.com/scala/scala-collection-contrib/issues/20
