### ISSUE TITLE
Tour: it's not immediately clear the hypothetical foldLeft with a single parameterlist doesn't compile

### ISSUE THREAD

**Issue by zuliandri2** [scala/docs.scala-lang#1647]
Hi all

may be this document need update
when I am run this code, it got error

![image](https://user-images.githubusercontent.com/10961433/75163557-091c3600-5752-11ea-8634-c606ab377842.png)

**Comment by martijnhoekstra** [comment]
That's correct. If `foldLeft` would have a single parameter list instead of multiple parameter lists, the code would look like that. But it doesn't, so the code doesn't look like that (but rather, like below).

Considering you didn't get that immediately, it's plausible that the language around that snippet could be clearer.

**Comment by zuliandri2** [comment]
Hi @martijnhoekstra 
when I run the code it say this
![andri@Andri-PC: ~-Downloads-idea-IU-193 5233 102-bin_008](https://user-images.githubusercontent.com/10961433/75169817-c8291f00-575b-11ea-9867-c3fae1a19c30.png)

please advice
Thank's

**Comment by martijnhoekstra** [comment]
That code shouldn't compile, it's an example what the code would look like of foldLeft had been defined with a single parameter list.

For concrete questions about how to do things, use gitter (https://gitter.im/scala/scala) or discourse:  (https://users.scala-lang.org/)

**Comment by zuliandri2** [comment]
Hi @martijnhoekstra 

noted, Thank's

**Comment by martijnhoekstra** [comment]
Reopening. IMO every case of misunderstood doc is an opportunity to improve. I'd like to see if I can phrase more clearly.
