### ISSUE TITLE
Add sort performance to collections/performance-characteristics.md

### ISSUE THREAD

**Issue by er1c** [scala/docs.scala-lang#1761]
Reference: https://github.com/scala/docs.scala-lang/blob/master/_overviews/collections/performance-characteristics.md

Sorting characteristics would also be useful to know here.

**Comment by NthPortal** [comment]
They all call `java.util.Arrays.sort` - that is, they sort by copying their contents to an `Array`, using Java's sort, and then rebuilding the collection - so they all have pretty much the same performance, with the following (fairly intuitive) exceptions:

- `sortInPlace` on `Array`-backed collections doesn't need to copy the collection to a new `Array` before sorting, or rebuild the collection after sorting.
- `sorted` on `Array`-backed collections has to copy the collection to a new `Array` before sorting, but can (probably) just wrap the `Array` it gets back without having to rebuild the collection from scratch.
- in some very esoteric cases where you sort a primitive collection with a non-default `Ordering`, it will use a custom merge sort rather than calling `java.util.Arrays.sort`, but it should have similar performance characteristics.

AFAIK, this is the case for all collections, but I didn't actually check, so it's possible there are one or two caveats I missed/forgot.

**Comment by SethTisue** [comment]
This could make a good addition to the Scaladoc for the sorting methods, but I don't think it's actionable in this repo.
