### ISSUE TITLE
Display Scala 3 doc above Scala 2 doc and remove WIP message

### ISSUE THREAD

**Issue by smarter** [scala/docs.scala-lang#2352]
On https://docs.scala-lang.org/, Scala 2 appears before Scala 3, and on all Scala 3 documentation pages like https://docs.scala-lang.org/scala3/new-in-scala3.html there's a message warning that the documentation is a "Work in Progress". Now that Scala 3 is the default for new users and that we've had time to fix the documentation, I think we should remove the warning and display the Scala 3 doc first.

**Comment by som-snytt** [comment]
What happened to the old saying, "Age before beauty"?

**Comment by julienrf** [comment]
Thank you @smarter for opening this issue.

I believe this is not an easy task. Also, before we can remove the “work in progress” message, the documentation needs to be stabilized…

That being said, we plan to work on this issue at the Scala Center, and here are my thoughts so far, feedback is welcome :)

- Instead of dividing the documentation between Scala 2 and Scala 3, unify them as much as possible (for some pages, that does not matter, e.g. the “collections guide”, but for other pages, we may have to duplicate the content, e.g. the Scala Book)
- Use [tabbed code blocks](https://github.com/clustergarage/jekyll-code-tabs) when relevant (e.g. Scala tour, collections guide, etc.) to show both Scala 2 and Scala 3 syntax on the same page,
- Unifying the documentation should avoid the combinatorial explosion of pages to maintain, due to translation
- Unifying the documentation should also remove the issue we have currently with the fact that the navigation menu is different for Scala 2 and Scala 3 content.

**Comment by smarter** [comment]
These all sounds like good improvements, but I don't think they preclude us from moving Scala 3 in front of Scala 2 on https://docs.scala-lang.org/, I think the current situation is confusing since the getting started page describes how to install Scala 3, but when going to the documentation page, it's easy to miss the "Scala 2" title and just click on "Tour of Scala" and learn the wrong version of Scala that way.

**Comment by smarter** [comment]
Also weird: on https://docs.scala-lang.org/ there is a "Language" dropdown in the "Scala 2" section, but it's not actually specific to Scala 2 and also changes the language of the Scala 3 section, so it should be moved above both sections.

**Comment by adpi2** [comment]
> These all sounds like good improvements, but I don't think they preclude us from moving Scala 3 in front of Scala 2 on https://docs.scala-lang.org/

I Upvote this. We should show Scala 3 on the top because we want newcomers to learn Scala by reading the Scala 3 book. The Scala 3 documentation is not as complete as the Scala 2 ones but I don't think it will confuse anyone if we move it up.
