### ISSUE TITLE
A guide to binary compatibility for library authors

### ISSUE THREAD

**Issue by lrytz** [scala/docs.scala-lang#621]
It would be great to have a guide about binary compatibility for library authors: what is a good policy to follow for your libraries, how to use version numbers, how to check binary compatibility using MiMa, details on what kind of changes are / aren't binary compatible.

**Comment by sjrd** [comment]
I've wanted to write such a guide for quite some time, now. But as with all things, time is lacking. I'd be happy to point a few ideas to someone motivated, though, as well as review such a guide.

**Comment by jvican** [comment]
I think this is a fantastic idea and everyone in the ecosystem would benefit from it. I would extend it to source compatibility also. Despite not having a tool to check it, it'd be good to give developers some rule of thumbs and guidelines.

**Comment by zjffdu** [comment]
Any update on this ? I also need some guidance on binary compatibility. Thanks

**Comment by heathermiller** [comment]
What about this? http://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html

**Comment by heathermiller** [comment]
So far, no one has stepped up to do this. 

All we have at the moment is a document which discusses [binary compatibility of Scala releases](http://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html). Not yet something specifically aimed at authors of libraries. 

However, maybe info from this guide is useful for general library authors? @sjrd @lrytz could you add a few sentences explaining what you had in mind for a document aimed specifically at library authors?

**Comment by sjrd** [comment]
There's a bunch of stuff to say about the topic.

* Explain why binary compatibility is an issue for library authors. Basically explain the diamond problem (in the dependency graph) and dependency hell when libraries evolve in binary incompatible ways.
* Talk about how language features impact binary compatibility: fields in traits, case classes, default parameters, type inference of result types, etc.
* Understand how to use MiMa, and how to interpret its output. Be able to diagnose whether its error messages can be safely filtered out or not.
* Give strategies on how to define public APIs so that they can be later evolved in source and binary compatible ways: avoid default parameters (prefer overloads), avoid case classes unless they are really meant for pattern matching (in which case they're frozen forever), seal/finalize everything possible, especially traits, use abstract classes instead of traits if new fields are expected in the future, etc.

There's *a lot* to say about this.

**Comment by heathermiller** [comment]
Thanks for the list, Séb. It's really helpful for someone to potentially use as a starting point.

**Comment by jvican** [comment]
I may step up to do this if someone does not beat me to it.

**Comment by DarkDimius** [comment]
There is also a SIP in works that would check that class does not use language features that may not be binary compatible across major Scala versions : http://docs.scala-lang.org/sips/pending/binary-compatibility.html

But I've currently put it on hold due to lack on time.

**Comment by jatcwang** [comment]
Hi I'm happy to help write this guide and to learn a thing or two myself along the way :)

**Comment by heathermiller** [comment]
@jatcwang Perhaps a good place to discuss with @DarkDimius and @jvican about how to organize the effort around writing such a guide is the scala/contributors gitter channel? (Just trying to get this discussion started)

**Comment by SethTisue** [comment]
it should say not to use the inliner, see e.g. https://github.com/scala/bug/issues/10489

**Comment by jatcwang** [comment]
That's a good example, thanks Seth. I'll jump on the channel to discuss my current draft.

**Comment by jvican** [comment]
Done in #881, closing!
