### ISSUE TITLE
use relative links now that GitHub Pages supports them?

### ISSUE THREAD

**Issue by SethTisue** [scala/docs.scala-lang#638]
https://github.com/blog/2290-relative-links-for-github-pages

this would make for a nice sitewide cleanup

**Comment by heathermiller** [comment]
Since we're no longer building on GitHub Pages, we'd need to add the plugin to do this. 

However what I don't understand is whether this requires permalinks? I'm currently struggling with permalinks over at scala-lang... Worried that if we change to permalinks, we'll break a bunch of links into docs.scala-lang 😟

**Comment by SethTisue** [comment]
> we're no longer building on GitHub Pages

I missed that... when/why did that happen?

does it make sense that we're still using the `github-pages` gem?
